version: "3.8"

services:
  openldap:
    image: osixia/openldap:1.1.8
    container_name: openldap
    networks:
      openldap:
    env_file:
      - .env
    environment:
      - LDAP_DOMAIN=${LDAP_DOMAIN_NAME}
      - LDAP_ADMIN_PASSWORD=${LDAP_ADMIN_PASSWORD}
    volumes:
      - ./ldap/data/database:/var/lib/ldap
      - ./ldap/data/config:/etc/ldap/slapd.d

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    networks:
      openldap:
    env_file:
      - .env
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=openldap
    ports:
      - "${PHPLDAP_ADMIN_PORT}:443"
    depends_on:
      - openldap

  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    networks:
      openldap:
    restart: always
    ports:
      - "8282:80"
    volumes:
      - ./gitlab/gitlab_home/config:/etc/gitlab
      - ./gitlab/gitlab_home/logs:/var/log/gitlab
      - ./gitlab/gitlab_home/data:/var/opt/gitlab
    shm_size: "256m"

  mongodb:
    image: docker.io/bitnami/mongodb:4.4
    container_name: mongodb
    restart: always
    networks:
      openldap:
    env_file:
      - .env
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=${MONGODB_REPLICA_SET_NAME:-rs0}
      - MONGODB_PORT_NUMBER=${MONGODB_PORT_NUMBER:-27017}
      - MONGODB_INITIAL_PRIMARY_HOST=${MONGODB_INITIAL_PRIMARY_HOST:-mongo}
      - MONGODB_INITIAL_PRIMARY_PORT_NUMBER=${MONGODB_INITIAL_PRIMARY_PORT_NUMBER:-27017}
      - MONGODB_ADVERTISED_HOSTNAME=${MONGODB_ADVERTISED_HOSTNAME:-mongo}
      - MONGODB_ENABLE_JOURNAL=${MONGODB_ENABLE_JOURNAL:-true}
      - ALLOW_EMPTY_PASSWORD=${ALLOW_EMPTY_PASSWORD:-yes}
    volumes:
      - mongodb_data:/bitnami/mongodb

  rocketchat:
    image: registry.rocket.chat/rocketchat/rocket.chat
    container_name: rocketchat
    restart: always
    networks:
      openldap:
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=${MONGO_URL}
      - MONGO_OPLOG_URL=${MONGO_OPLOG_URL}
      - ROOT_URL=${ROOT_URL}
      - PORT=${ROCKETCHAT_PORT}
      - DEPLOY_METHOD=${DEPLOY_METHOD}
    depends_on:
      - mongodb

volumes:
  mongodb_data:
    driver: local

networks:
  openldap:
    driver: bridge
    ipam:
      config:
        - subnet: 172.31.0.0/16
          gateway: 172.31.0.1
